<?php

return [
    'candidate' => 1,
    'employer' => 2,
    'admin' => 3,
    'unconfirmed' => 0,
    'confirmed' => 1,
    'block' => 2,
    'skill' => 1,
    'language' => 2,
    'working_time' => 3,
    'date_time' => "Y-m-d h:i:sa",
    'pdf' => "application/pdf",
    'png' => "image/png",
    'jpg' => "image/jpeg",
    'upload_company' => "/upload/company/",
    'upload_user' => "/upload/user/",
    'avatar' => 1,
    'admin' => 3,
    'logo' => 'images/logo.png',
    'default_avatar' => "https://res.cloudinary.com/dfihy5b0d/image/upload/v1621871350/ikbo6ftxnfboiolsbcmv.png",
    'default_avatar_company' => 'https://res.cloudinary.com/dfihy5b0d/image/upload/v1621871816/d6x7iyfiywdf2pw3ehwu.png',
    'limit' => 10,
    'en' => 'en',
    'vi' => 'vi',
    'phone' => '0914249080',
    'email' => 'haunt0607@gmail.com',
];
